name: Release GitHub Action

on:
  push:
    branches:
      - main

env:
  image: ghcr.io/${{ github.repository }}/bilayer-yaml-validation
  dockerhub_image: ${{ secrets.DOCKER_USER }}/bilayer-yaml-validation

jobs:
  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate version tags
        run: |
          version=$(cat version)
          echo "version=${version}" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build --tag ${image}:${GITHUB_SHA} --tag ${image}:latest --tag ${image}:${version} .
      - name: Push Docker image to GitHub
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${image}:${GITHUB_SHA}
          docker push ${image}:${version}
          docker push ${image}:latest
